#server.port: 8443
server.port: 8080

spring.cloud.gateway.routes:

  - id: product-composite
    uri: http://product-composite
    predicates:
      - Path=/product-composite/**

  - id: product-composite-swagger-ui
    uri: http://product-composite
    predicates:
      - Path=/openapi/**

  - id: product-composite-swagger-ui-webjars
    uri: http://product-composite
    predicates:
      - Path=/webjars/**

  - id: configserver
    uri: ${spring.cloud.config.uri}
    predicates:
      - Path=/config/**
    filters:
      - RewritePath=/config/(?<segment>.*), /$\{segment}

spring.security.oauth2.resourceserver.jwt.issuer-uri: "http://${app.auth-server}:8080/realms/master"

#spring.sleuth.reactor.instrumentation-type: decorate-on-last

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE


